services:
  kibana:
    container_name: kibana
    # image: kibana:9.0.2
    image: kibana
    build: .
    volumes:
      - kb_data:/usr/share/kibana/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3
    environment:
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
    networks:
      - elk-network

volumes:
  kb_data:
    name: elk_es_data


networks:
  elk-network:
    external: true