services:
  kibana:
    image: kibana:${KIBANA_VERSION}
    container_name: kibana
    volumes:
      - kb_data:/usr/share/kibana/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3
    environment:
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
      SERVER_NAME: kibana
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS}
      MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: true
      XPACK_SECURITY_AUTHC_PROVIDERS_BASIC_BASIC1_ORDER: 0

volumes:
  kb_data:
    name: kb_data
