# Docker Compose override for Keycloak external network integration
# Usage: Used with --keycloak-network flag to enable external keycloak-network connectivity

services:
  # Add keycloak-network to kibana service
  kibana:
    networks:
      - keycloak-network

  # Helper service to ensure keycloak network exists and provide bridge connectivity
  keycloak-network-bridge:
    image: alpine:latest
    container_name: kibana-keycloak-bridge
    profiles:
      - keycloak-network
    command: [ "echo", "Keycloak network bridge active" ]
    networks:
      - keycloak-network
    depends_on:
      - kibana

networks:
  keycloak-network:
    name: keycloak-network
    external: true
