services:
  kibana:
    environment:
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      STEP_CA_TRUST: ${STEP_CA_TRUST}
    networks:
      - step-ca-network

networks:
  step-ca-network:
    name: step-ca-network
    external: true
